version: '3.3'
services:

  db-service:
    image: postgres
    container_name: db-service
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=msb
    volumes:
      - ./db:/var/lib/postgresql/data

  mongo-service:
    image: mongo
    container_name: mongo-service
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: marieservanebellet
    volumes:
      - mongo-volume:/data/db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pictures-service:
    container_name: pictures-service
    image: dceoy/nginx-autoindex    # if autoindex does not work, delete html files !
    ports:
      - 80:80
    volumes:
      - pictures-volume:/var/lib/nginx/html

  mail-catcher:
    image: schickling/mailcatcher
    container_name: mail-catcher
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  mongo-volume:
    external: true
  pictures-volume:
    external: true
