version: '3.3'
services:

  mongo-service:
    image: mongo
    container_name: mongo-service
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: marieservanebellet
    volumes:
      - mongo-volume:/data/db

  pictures-service:
    container_name: pictures-service
    image: nginx
    ports:
      - 80:80
    volumes:
      - pictures-volume:/usr/share/nginx/html/

  mail-catcher:
    image: schickling/mailcatcher
    container_name: mail-catcher
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  mongo-volume:
    external: true
  pictures-volume:
    external: true
