version: '3.3'
services:

  mongo-service:
    image: mongo
    container_name: mongo-service
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: marieservanebellet
    volumes:
      - ./mongo-seeder/:/docker-entrypoint-initdb.d/

  pictures-service:
    container_name: pictures-service
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./pictures/:/usr/share/nginx/html/
