services:

  db:
    image: postgres:17
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=msb
    volumes:
      - ./db-data:/var/lib/postgresql/data

  pictures:
    container_name: pictures
    image: dceoy/nginx-autoindex    # if autoindex does not work, delete html files !
    ports:
      - 80:80
    volumes:
      - ./pictures:/var/lib/nginx/html

  mail-catcher:
    image: schickling/mailcatcher
    container_name: mail-catcher
    ports:
      - 1080:1080
      - 1025:1025
