version: '3.3'
services:

  db-service:
    image: postgres:15
    container_name: db-service
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=msb
    volumes:
      - db-volume:/var/lib/postgresql/data

  pictures-service:
    container_name: pictures-service
    image: dceoy/nginx-autoindex    # if autoindex does not work, delete html files !
    ports:
      - 80:80
    volumes:
      - pictures-volume:/var/lib/nginx/html

  mail-catcher:
    image: schickling/mailcatcher
    container_name: mail-catcher
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  db-volume:
    external: true
  pictures-volume:
    external: true
