version: '3.3'
services:

  front-service:
    image: "ghcr.io/eloiblt/marieservanebellet-front:latest"
    container_name: front-service
    build:
      context: ../../
      dockerfile: ./front/Dockerfile
    networks:
      - front-network

  api-service:
    image: "ghcr.io/eloiblt/marieservanebellet-api:latest"
    container_name: api-service
    build:
      context: ../../
      dockerfile: ./api/Dockerfile
    networks:
      - api-network
    depends_on:
      - mongo-service

  mongo-service:
    image: mongo
    container_name: mongo-service
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: marieservanebellet
    volumes:
      - mongo-volume:/data/db/
    networks:
      - api-network

  pictures-service:
    image: nginx
    container_name: pictures-service
    networks:
      - pictures-network
    volumes:
      - pictures-volume:/usr/share/nginx/html

  reverse-proxy:
    image: "ghcr.io/eloiblt/marieservanebellet-reverse-proxy:latest"
    container_name: reverse-proxy
    build:
      context: ./reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/marieservanebellet.com/:/etc/nginx/ssl # only in prod
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - api-network
      - front-network
      - pictures-network
    depends_on:
      - front-service
      - api-service
      - pictures-service

networks:
  api-network:
    driver: bridge
  front-network:
    driver: bridge
  pictures-network:
    driver: bridge

volumes:
  mongo-volume:
  pictures-volume:
