services:

  msb-frontend:
    image: ghcr.io/eloiblt/marieservanebellet-front:${IMAGE_TAG:-latest}
    build:
      context: ../../
      dockerfile: ./front/Dockerfile

  msb-backend:
    image: ghcr.io/eloiblt/marieservanebellet-api:${IMAGE_TAG:-latest}
    build:
      context: ../../
      dockerfile: ./api/Dockerfile