version: '3.3'
services:

  front-service:
    container_name: front-service
    build:
      context: ../../
      dockerfile: ./front/Dockerfile
    networks:
      - front-network

  api-service:
    container_name: api-service
    build:
      context: ../../
      dockerfile: ./api/Dockerfile
    networks:
      - api-network
    depends_on:
      - mongo-service

  mongo-service:
    image: mongo
    container_name: mongo-service
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: marieservanebellet
    volumes:
      - ./../dev/mongo-seeder/:/docker-entrypoint-initdb.d/ # remove prod
    networks:
      - api-network

  pictures-service:
    container_name: pictures-service
    image: nginx
    networks:
      - pictures-network
    volumes:
      - ./../dev/pictures:/usr/share/nginx/html # remove prod

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done &
      nginx -g \"daemon off;\"'"
    networks:
      - api-network
      - front-network
      - pictures-network
      - certbot-network
    depends_on:
      - front-service
      - api-service
      - pictures-service

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email
      eloi.bellet@gmail.com --agree-tos --no-eff-email -d marieservanebellet.com
      -d www.marieservanebellet.com
    networks:
      - certbot-network

networks:
  api-network:
    driver: bridge
  front-network:
    driver: bridge
  pictures-network:
    driver: bridge
  certbot-network:
    driver: bridge
