version: '3.3'
services:

  msb-frontend:
    image: "ghcr.io/eloiblt/marieservanebellet-front:latest"
    container_name: msb-frontend
    restart: always
    build:
      context: ../../
      dockerfile: ./front/Dockerfile
    ports:
      - 3000:80
    # networks:
    #   - front-network

  msb-backend:
    image: "ghcr.io/eloiblt/marieservanebellet-api:latest"
    container_name: msb-backend
    restart: always
    build:
      context: ../../
      dockerfile: ./api/Dockerfile
    volumes:
      - pictures-volume:/pictures
    ports:
      - 3001:4000
    networks:
      - backend-network
    depends_on:
      - msb-db

  msb-db:
    image: postgres:15
    container_name: msb-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=msb
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - backend-network

  msb-pictures:
    image: nginx
    container_name: msb-pictures
    restart: always
    ports:
      - 3002:80
    volumes:
      - pictures-volume:/usr/share/nginx/html
    # networks:
    #   - pictures-network

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - backend-network

  # reverse-proxy:
  #   image: "ghcr.io/eloiblt/marieservanebellet-reverse-proxy:latest"
  #   container_name: reverse-proxy
  #   restart: always
  #   build:
  #     context: ../../
  #     dockerfile: ./docker/prod/reverse-proxy/Dockerfile
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /etc/letsencrypt/:/etc/nginx/ssl
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  #   networks:
  #     - backend-network
  #     - front-network
  #     - pictures-network
  #   depends_on:
  #     - frontend
  #     - backend
  #     - pictures

networks:
  backend-network:
    driver: bridge
  # front-network:
  #   driver: bridge
  # pictures-network:
  #   driver: bridge

volumes:
  db-volume:
    external: true
  pictures-volume:
    external: true
