name: CI - CD

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # sonarcloud:
  #   name: SonarCloud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the stack
        working-directory: ./docker/prod
        run: docker-compose build
      - name: Push the stack
        working-directory: ./docker/prod
        run: docker-compose push
        
  # build:
  #   needs: sonarcloud
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: executing remote ssh commands using password
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.VPS_IP }}
  #         username: ubuntu
  #         password: ${{ secrets.VPS_PWD }}
  #         port: ${{ secrets.VPS_PORT }}
  #         script: |
  #           whoami
  #           ls -al
