name: CI - CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push:
    needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io -u "${GITHUB_ACTOR}" --password-stdin

      - name: Build the stack
        working-directory: ./docker/prod
        run:
          # echo ${{ secrets.MAIL_BCC }} | sed -e 's/\(.\)/\1 /g'       # debug
          docker-compose build --build-arg FRONT_URL=${{ secrets.FRONT_URL }} --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} --build-arg SMTP_HOST=${{ secrets.SMTP_HOST }} --build-arg SMTP_PORT=${{ secrets.SMTP_PORT }} --build-arg SMTP_TLS=${{ secrets.SMTP_TLS }} --build-arg SMTP_USER=${{ secrets.SMTP_USER }} --build-arg SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} --build-arg MAIL_TO=${{ secrets.MAIL_TO }} --build-arg MAIL_BCC=${{ secrets.MAIL_BCC }}

      - name: Push the stack
        working-directory: ./docker/prod
        run: docker-compose push

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PWD }}
          port: ${{ secrets.VPS_PORT }}
          source: "docker/prod/docker-compose.yml"
          target: "scp"

      - name: remove old docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PWD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~
            rm docker-compose.yml
            cp scp/docker/prod/docker-compose.yml .
            rm -r scp
            echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
            whoami
            ls -al
